server:
  port: 8088
spring:
  messages:
    basename: messages
    encoding: UTF-8
  security:
    user:
      name: username
      password: passwOrd
management:
  endpoints:
    web:
      exposure:
        include: "*"
