server:
  port: 8088
spring:
  messages:
    basename: messages
    encoding: UTF-8
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
#  security:
#    user:
#      name: username
#      password: passwOrd
management:
  endpoints:
    web:
      exposure:
        include: "*"
